export {PrivateRoute} from './PrivateRoutes/PrivateRoute'
export {HomePage}     from './HomePage'
export {Login}        from './Login'
export {Register}        from './Register'
export {Private}      from './Private'